### ISSUE TITLE
使用FCN选项发现模型过拟合严重

### ISSUE THREAD

**Issue by XuDongHecs** [ShenhanQian/Lane_Detection-An_Instance_Segmentation_Approach#2]
![image](https://user-images.githubusercontent.com/23398504/77778084-72fa6900-708b-11ea-996d-ab6a211bf407.png)

**Comment by ShenhanQian** [comment]
Tusimple Challenge数据集较小，且variation较小，用ENet就已经足够。FCN和ICNet可以用在更难的数据集上。
