### ISSUE TITLE
Error(s) in loading state_dict for LaneNet_ENet_1E1D

### ISSUE THREAD

**Issue by hejinIzhanghao** [ShenhanQian/Lane_Detection-An_Instance_Segmentation_Approach#3]
@ShenhanQian 

cannot load the 'ckpt_ENet-1E1D-b1d0.01-v0.2d1_epoch-10.pth'

it said `Missing key(s) in state_dict`

**Comment by ShenhanQian** [comment]
You can set the `strict=false` param when loading the checkpoint. Then you will see we exactly are missing, or whether any other problem triggered this error.
